# Bot login settings
mw_server_url: 'http://example.com'
mw_server_path: '/wiki'
mw_username: 'username'
mw_password: 'password'
mw_server_port: false

# Custom Settings
uploadWikiPages: true
deleteWikiPages: false
