language: node_js
node_js:
  - '0.10'
  - '0.12'
  - 'iojs'
before_install:
  - export CODACY_PROJECT_TOKEN=a7daff185e694c3d853bb35cbc6405c8
before_script:
  - npm install -g grunt-cli
addons:
  code_climate:
    repo_token: 8b18cab11dc6aec1a9e220cd2981ea1a7947d116a868d4370c1bd5f2b264c07e
notifications:
  email:
    on_success: [never] # default: change
    on_failure: [always] # default: always
    recipients:
      - info@fannon.de
after_script:
  - cat coverage/lcov.info | codeclimate
  - cat coverage/lcov.info | ./node_modules/codacy-coverage/bin/codacy-coverage.js
after_success:
