language: node_js
node_js:
  - '0.10'
  - '0.12'
before_install:
  sudo pip install codecov
before_script:
  - npm install -g grunt-cli
notifications:
  email:
    on_success: [never] # default: change
    on_failure: [always] # default: always
    recipients:
      - info@fannon.de

after_success:
  codecov