env:
- CODECLIMATE_REPO_TOKEN=8b18cab11dc6aec1a9e220cd2981ea1a7947d116a868d4370c1bd5f2b264c07e codeclimate-test-reporter

language: node_js
node_js:
  - '0.10'
  - '0.12'
  - 'iojs'
before_install:

before_script:
  - npm install -g grunt-cli
  - npm install -g codeclimate-test-reporter
addons:
  code_climate:
    repo_token: 8b18cab11dc6aec1a9e220cd2981ea1a7947d116a868d4370c1bd5f2b264c07e
notifications:
  email:
    on_success: [never] # default: change
    on_failure: [always] # default: always
    recipients:
      - info@fannon.de
after_script:
  - cat coverage/lcov.info | codeclimate
  - codeclimate-test-reporter < coverage/lcov.info
after_success:
