language: node_js
node_js:
  - '0.10'
  - '0.12'
before_script:
  - npm install -g grunt-cli
notifications:
  email:
    on_success: [never] # default: change
    on_failure: [always] # default: always
after_success:
  - coveralls